"""add_learning_coach_models

Revision ID: 9eef91f86ba6
Revises: 
Create Date: 2025-12-10 15:17:29.164277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = '9eef91f86ba6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def get_json_type():
    """根据数据库方言返回合适的 JSON 类型"""
    from alembic import context
    dialect = context.get_context().dialect.name
    if dialect == 'postgresql':
        from sqlalchemy.dialects.postgresql import JSONB
        return JSONB(astext_type=Text())
    else:
        return sa.JSON()


def upgrade() -> None:
    """Upgrade schema."""
    json_type = get_json_type()
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=50), nullable=False, comment='项目 ID，格式：proj_xxxxxxxxxxxx'),
    sa.Column('repo_url', sa.String(length=512), nullable=False, comment='Git 仓库地址'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='项目名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('archetype', sa.String(length=50), nullable=True, comment='项目原型：web_backend, library, agent_framework 等'),
    sa.Column('primary_language', sa.String(length=50), nullable=True, comment='主要编程语言'),
    sa.Column('framework', sa.String(length=100), nullable=True, comment='使用的主要框架'),
    sa.Column('profile', json_type, nullable=True, comment='项目画像 JSON（由 Profiler Agent 生成）'),
    sa.Column('repo_map', json_type, nullable=True, comment='仓库结构映射 JSON（由 Mapper Agent 生成）'),
    sa.Column('capabilities', json_type, nullable=True, comment='识别出的能力模块列表'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='项目状态：pending, cloning, analyzing, indexing, ready, failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息（如果处理失败）'),
    sa.Column('local_path', sa.String(length=512), nullable=True, comment='本地克隆路径'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删除）'),
    sa.PrimaryKeyConstraint('id'),
    comment='项目表，存储待学习的代码仓库信息'
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_projects_archetype', ['archetype'], unique=False)
        batch_op.create_index('ix_projects_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_projects_status', ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户 ID'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='用户邮箱'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='用户名'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删除）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    comment='用户表（当前为占位，单租户场景）'
    )
    op.create_table('analysis_documents',
    sa.Column('id', sa.String(length=50), nullable=False, comment='文档 ID，格式：doc_xxxxxxxxxxxx'),
    sa.Column('project_id', sa.String(length=50), nullable=False, comment='关联的项目 ID'),
    sa.Column('section_type', sa.String(length=50), nullable=False, comment='章节类型：executive_summary, system_architecture, core_components 等'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='章节标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='章节内容（Markdown 格式）'),
    sa.Column('version', sa.Integer(), nullable=False, comment='文档版本号'),
    sa.Column('metadata', json_type, nullable=True, comment='额外元数据，如生成参数、引用的代码片段等'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='章节排序索引'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删除）'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'section_type', 'version', name='uq_analysis_documents_project_section_version'),
    comment='分析文档表，存储项目的九大章节分析文档'
    )
    with op.batch_alter_table('analysis_documents', schema=None) as batch_op:
        batch_op.create_index('ix_analysis_documents_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_analysis_documents_section_type', ['section_type'], unique=False)

    op.create_table('file_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('owner_id', sa.Integer(), nullable=True, comment='归属用户ID（可为空）'),
    sa.Column('storage_type', sa.String(length=16), server_default=sa.text("'local'"), nullable=False, comment='存储类型：local/s3/oss'),
    sa.Column('bucket', sa.String(length=255), nullable=True, comment='存储桶/容器名称'),
    sa.Column('region', sa.String(length=64), nullable=True, comment='区域名（可为空）'),
    sa.Column('key', sa.String(length=512), nullable=False, comment='对象存储中的Key（路径）'),
    sa.Column('unique_key_hash', sa.String(length=64), nullable=False, comment='唯一键哈希：SHA-256(storage_type|bucket|key)'),
    sa.Column('size', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='文件大小（字节）'),
    sa.Column('etag', sa.String(length=64), nullable=True, comment='存储返回的ETag/校验值'),
    sa.Column('content_type', sa.String(length=100), nullable=True, comment='MIME类型'),
    sa.Column('original_filename', sa.String(length=255), nullable=True, comment='原始文件名'),
    sa.Column('kind', sa.String(length=50), nullable=True, comment='业务分类，如 avatar/document'),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否公共可读'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='扩展元数据（JSON）'),
    sa.Column('url', sa.String(length=1024), nullable=True, comment='公共/CDN URL快照（可选）'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='文件状态：pending/active/deleted'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删除）'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_key_hash'),
    comment='文件资源表，记录对象存储中的文件元数据'
    )
    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.create_index('ix_file_assets_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_file_assets_owner_created', ['owner_id', 'created_at'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.String(length=50), nullable=False, comment='问题 ID，格式：q_xxxxxxxxxxxx'),
    sa.Column('project_id', sa.String(length=50), nullable=False, comment='关联的项目 ID'),
    sa.Column('template_id', sa.String(length=100), nullable=True, comment='问题模板 ID'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='问题标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='问题详细描述'),
    sa.Column('stage', sa.String(length=50), nullable=False, comment='所属学习阶段'),
    sa.Column('difficulty', sa.String(length=20), nullable=False, comment='问题难度：beginner, intermediate, advanced, expert'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='在同阶段内的排序索引'),
    sa.Column('recommended_files', json_type, nullable=True, comment='推荐阅读的文件路径列表'),
    sa.Column('prerequisites', json_type, nullable=True, comment='前置问题 ID 列表'),
    sa.Column('hints', json_type, nullable=True, comment='提示列表，逐步引导学习者'),
    sa.Column('expected_answer_points', json_type, nullable=True, comment='期望的答案要点，用于评估'),
    sa.Column('tags', json_type, nullable=True, comment='标签列表'),
    sa.Column('capability_module', sa.String(length=50), nullable=True, comment='关联的能力模块'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删除）'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='问题表，存储为项目生成的学习问题'
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index('ix_questions_capability_module', ['capability_module'], unique=False)
        batch_op.create_index('ix_questions_difficulty', ['difficulty'], unique=False)
        batch_op.create_index('ix_questions_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_questions_project_stage', ['project_id', 'stage'], unique=False)
        batch_op.create_index('ix_questions_stage', ['stage'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=50), nullable=False, comment='会话 ID，格式：sess_xxxxxxxxxxxx'),
    sa.Column('project_id', sa.String(length=50), nullable=False, comment='关联的项目 ID'),
    sa.Column('learning_mode', sa.String(length=20), nullable=False, comment='学习模式：macro（宏观学习）, capability（能力深挖）'),
    sa.Column('current_stage', sa.String(length=50), nullable=False, comment='当前学习阶段'),
    sa.Column('progress', json_type, nullable=True, comment='学习进度 JSON，包含已完成的问题、正确率等'),
    sa.Column('selected_capabilities', json_type, nullable=True, comment='选中的能力模块列表（能力深挖模式）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='会话状态：active, paused, completed, abandoned'),
    sa.Column('summary', sa.Text(), nullable=True, comment='会话总结（完成时生成）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删除）'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='学习会话表，跟踪用户的学习进度'
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_sessions_learning_mode', ['learning_mode'], unique=False)
        batch_op.create_index('ix_sessions_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_sessions_status', ['status'], unique=False)

    op.create_table('learning_records',
    sa.Column('id', sa.String(length=50), nullable=False, comment='学习记录 ID，格式：lr_xxxxxxxxxxxx'),
    sa.Column('session_id', sa.String(length=50), nullable=False, comment='关联的会话 ID'),
    sa.Column('question_id', sa.String(length=50), nullable=False, comment='关联的问题 ID'),
    sa.Column('answer', sa.Text(), nullable=True, comment='用户的回答内容'),
    sa.Column('evaluation', json_type, nullable=True, comment='评估结果 JSON，包含各要点的匹配情况'),
    sa.Column('score', sa.Float(), nullable=True, comment='得分（0-100）'),
    sa.Column('is_correct', sa.Boolean(), nullable=True, comment='是否回答正确'),
    sa.Column('explanation', json_type, nullable=True, comment='讲解内容 JSON（由 Explainer Agent 生成）'),
    sa.Column('feedback', sa.Text(), nullable=True, comment='Tutor 的反馈和引导'),
    sa.Column('time_spent', sa.Integer(), nullable=True, comment='用时（秒）'),
    sa.Column('attempt_number', sa.Integer(), nullable=False, comment='尝试次数'),
    sa.Column('hints_used', sa.Integer(), nullable=False, comment='使用的提示数量'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删除）'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='学习记录表，存储用户的回答和评估结果'
    )
    with op.batch_alter_table('learning_records', schema=None) as batch_op:
        batch_op.create_index('ix_learning_records_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_learning_records_question_id', ['question_id'], unique=False)
        batch_op.create_index('ix_learning_records_session_id', ['session_id'], unique=False)
        batch_op.create_index('ix_learning_records_session_question', ['session_id', 'question_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.String(length=50), nullable=False, comment='笔记 ID，格式：note_xxxxxxxxxxxx'),
    sa.Column('session_id', sa.String(length=50), nullable=False, comment='关联的会话 ID'),
    sa.Column('question_id', sa.String(length=50), nullable=True, comment='关联的问题 ID（可选）'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='笔记标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='笔记内容（Markdown 格式）'),
    sa.Column('highlights', json_type, nullable=True, comment='高亮内容列表，包含选中文本和位置信息'),
    sa.Column('tags', json_type, nullable=True, comment='标签列表'),
    sa.Column('source_file', sa.String(length=512), nullable=True, comment='关联的源文件路径'),
    sa.Column('source_lines', json_type, nullable=True, comment='关联的代码行范围，如 {start: 10, end: 20}'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删除）'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='笔记表，存储用户的学习笔记'
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index('ix_notes_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_notes_question_id', ['question_id'], unique=False)
        batch_op.create_index('ix_notes_session_id', ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index('ix_notes_session_id')
        batch_op.drop_index('ix_notes_question_id')
        batch_op.drop_index('ix_notes_created_at')

    op.drop_table('notes')
    with op.batch_alter_table('learning_records', schema=None) as batch_op:
        batch_op.drop_index('ix_learning_records_session_question')
        batch_op.drop_index('ix_learning_records_session_id')
        batch_op.drop_index('ix_learning_records_question_id')
        batch_op.drop_index('ix_learning_records_created_at')

    op.drop_table('learning_records')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_status')
        batch_op.drop_index('ix_sessions_project_id')
        batch_op.drop_index('ix_sessions_learning_mode')
        batch_op.drop_index('ix_sessions_created_at')

    op.drop_table('sessions')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index('ix_questions_stage')
        batch_op.drop_index('ix_questions_project_stage')
        batch_op.drop_index('ix_questions_project_id')
        batch_op.drop_index('ix_questions_difficulty')
        batch_op.drop_index('ix_questions_capability_module')

    op.drop_table('questions')
    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.drop_index('ix_file_assets_owner_created')
        batch_op.drop_index('ix_file_assets_created_at')

    op.drop_table('file_assets')
    with op.batch_alter_table('analysis_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_analysis_documents_section_type')
        batch_op.drop_index('ix_analysis_documents_project_id')

    op.drop_table('analysis_documents')
    op.drop_table('users')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_status')
        batch_op.drop_index('ix_projects_created_at')
        batch_op.drop_index('ix_projects_archetype')

    op.drop_table('projects')
    # ### end Alembic commands ###
